### PR TITLE
Add CC0 license statement

### PR DESCRIPTION
**Pull request by noahgibbs**
Christopher Allen has asked me to put up a public statement, relicensing my old Phantasmal and web site content as CC0. Can I ask you to add this statement to the Phantasmal repository?

### CODE REVIEW

**Comment by dworkin** [comment]
Interesting.

I created this repository as a way of consolidating the history from different source repositories, when it seemed like that history might get lost through negligent treatment.  That was my _entire_ contribution.

@shentino then forked the repo and continued to work on it, as he had been before. Shouldn't you be asking him to add the CC0 license rather than me? Since my repo already contains his contributions, I would need his permission to add the license even to _my_ repository.

If there is a disagreement between you and @shentino about the license, I'd suggest that you fork my repository, roll back to your last own commit, and then add the license in a new commit. @ChristopherA can then fork your repository for ChatTheatre.

**Comment by shentino** [comment]
I released it under the AGPLv3 IIRC.

In theory the licensing documentation SHOULD reflect that at this point?

**Comment by shentino** [comment]
https://github.com/dworkin/phantasmal/blob/master/mudlib/COPYING

**Comment by noahgibbs** [comment]
Yes. Christopher Allen is asking about re-releasing, especially the web site, as documentation. I can understand why he wouldn't favour the AGPL, which isn't especially designed for content. He's asked me if I'll re-license what I wrote (and I will.) My earlier email to you, Raymond, was to ask if you found relicensing of that sort acceptable. If you don't, then the obvious thing for me to do is to take (only) my own contributions to the web site and release them as CC0. If Chris is fine with AGPL then I'm not opposed to it. But he has specifically asked me about relicensing as CC0/public domain, which suggests that he is not.

**Comment by shentino** [comment]
Actually the website itself was released under the GFDL, but since I'm the
only contributor after you I can relicense it pretty much how you need it.
Please tell me what you need.

**Comment by shentino** [comment]
I, Raymond Jennings, do hereby release the entire content of the website to the world as public domain.

With the caveat that it is a derived work itself, that included stuff from elsewhere, such as the DGD list, that I may not have the authority to relicense.

**Comment by noahgibbs** [comment]
Perfect. Thank you. It would be great if you could add a file to that
effect - basically update/replace the file in the PR with one saying
roughly this.

I recommend saying you license it CC0 since it's not clear that you *can*
just declare something to be public domain in the US, but CC0 is the same
rights in a formal license.

**Comment by shentino** [comment]
[website.tar.gz](https://github.com/dworkin/phantasmal/files/5114491/website.tar.gz)
I hereby release this file to the world under the GPL, AGPL, CC everything, public domain, what have you.

Caveat: I can't redeclare someone else's copyright so be mindful of inclusions that were extraced from elsewhere.  This deletes the makefiles, the packages, and the website build scripts, but preserves the base documentation as well as the included snippets from the DGDML.

**Comment by dworkin** [comment]
Glad that the two of you have found each other.  It seems like a pull request for @shentino's phantasmal repository is the next step.

**Comment by ChristopherA** [comment]
Unfortunately this isn't sufficient under US law. Some details on why are here: https://creativecommons.org/share-your-work/public-domain/cc0/

But the upshot is that you both (Shentino & Noah) as US citizens should add this text as a PR to the README.md of this repo, (I'ld like to suggest also my kernellib fork as I'm integrating lots of docs soley about kernellib there too). Ideally the commit should be signed with GPG, but as long as you submit the PR via GitHub it will log your account which should be sufficient under law.

Here is mine:

<p xmlns:dct="http://purl.org/dc/terms/" xmlns:vcard="http://www.w3.org/2001/vcard-rdf/3.0#">
  <a rel="license"
     href="http://creativecommons.org/publicdomain/zero/1.0/">
    CC0
  </a>
  <br />
  To the extent possible under law,
  <a rel="dct:publisher"
     href="https://christophera.info">
    <span property="dct:title">Christopher Allen</span></a>
  has waived all copyright and related or neighboring rights to
  <span property="dct:title">DGD Kernel Library (aka `kernellib`)</span>.
This work is published from:
<span property="vcard:Country" datatype="dct:ISO3166"
      content="US" about="https://github.com/ChatTheatre/kernellib">
  United States</span>.
</p>

If you want to add your caveat after that special text above, that is fine: i.e. Caveat: I can't redeclare someone else's copyright so be mindful of inclusions that were extraced from elsewhere. This deletes the makefiles, the packages, and the website build scripts, but preserves the base documentation as well as the included snippets from the DGDML."

I'd love it if Felix also posted that CC special text into the README of the kernellib as well, as though he is not a US Citizen, declaring that something public domain is a bit more complicated in the EU as well. The CC agreement is global.

-- Christopher Allen

**Comment by ChristopherA** [comment]
Do note that you need to use the raw text of above, i.e. put this (without the markdown code fences)  into the README.md:

```
<p xmlns:dct="http://purl.org/dc/terms/" xmlns:vcard="http://www.w3.org/2001/vcard-rdf/3.0#">
  <a rel="license"
     href="http://creativecommons.org/publicdomain/zero/1.0/">
    <img src="http://i.creativecommons.org/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" />
  </a>
  <br />
  To the extent possible under law,
  <a rel="dct:publisher"
     href="https://christophera.info">
    <span property="dct:title">Christopher Allen</span></a>
  has waived all copyright and related or neighboring rights to
  <span property="dct:title">DGD Kernel Library (aka `kernellib`)</span>.
This work is published from:
<span property="vcard:Country" datatype="dct:ISO3166"
      content="US" about="https://github.com/ChatTheatre/kernellib">
  United States</span>.
</p>
```

**Comment by dworkin** [comment]
Sorry @ChristopherA, I'm not going to change anything. As far as I'm concerned, code and documentation of which I am the author and which I released into the public domain, is in the public domain. If the US and EU want to collapse under the weight of their legal systems, that is their affair.

**Comment by ChristopherA** [comment]
You can see an example of how I've done this declaration for myself and the two corporations that might have owned some rights (for instance everything that Par Winzell & Erwin did related to DGD while they were employees hypothetically belonged to Skotos Tech Corporation). This way anyone relying on this repo knows that they can rely on it, and the kernellib it describes, as public domain.

https://github.com/ChatTheatre/kernellib/blob/master/README.md

FYI, this fork is mostly I'm tracking @dworkin's last version of the kernellib plus a few of Shentino's changes since (and may eventually revert some of them if they don't make sense).  I am adding only information SPECIFICALLY about the combination of DGD with the Kernelib (not other forks, not Phantasmal or SkotOS), so that people can get in one place what the core of what DGD and the kernellib as to offer before looking at other solutions. 

I'm trying to be careful and that verything I add to it, and anything that I add from Skotos Tech or the new company Dyvers Hands is public domain. Once I get PD declarations from @noahgibbs and @shentino there is a lot I can add and organize here.

-- Christopher Allen

**Comment by ChristopherA** [comment]
> Sorry @ChristopherA, I'm not going to change anything. As far as I'm concerned, code and documentation of which I am the author and which I released into the public domain, is in the public domain. If the US and EU want to collapse under the weight of their legal systems, that is their affair.

@dworkin — I understand. I'm a leader in the Bitcoin and Blockchain community, and there are many who feel the way you do. I think your current declaration is probably good enough.  I just have to be more careful.

Part of the point of [Blockchain Commons][https://github.com/BlockchainCommons) is that a lot of common infrastructure isn't getting the financial support that it needs for the long term, and from my experience with SSL/TLS a lot of legacy knowledge and skills is being lost or outdated, or risk collapse due to things like HeartBleed.

I know that you've been frustrated with this problem over the last two decades. So I'm just applying my principles that I'm using in thinking about long-term support of Bitcoin to my stewardship of the SkotOS player communities. I'm using my best practices of how open source communities behave today to get financial patronage (@BlockchainCommons is a not-for-profit and gets $10-20K a month and growing).

I'm particular frustrated at myself for not puzzling out how to help you make DGD what node.js is today. I think it could have been a better solution. I wish there was an answer for Hydra as well.

I'm also frustrated at myself for not focusing more resources 20 years ago at making sure that all SkotOS did was better documented. I actually think we did better than most, but not good enough. I'm paying a big price for that now as I'm trying to pass on all our games to their communities for long-term support in case I'm not around any longer. I consider that part of being a good steward.

But unfortunately a lot of information and details of architecture of SkotOS has become lost, and I fear without reverse engineering some things now, that Par, Erwin, and to a lesser extent Kalle, understood. They haven't been working on it for 15 years, and have forgotten much and are no longer interested in supporting. So it is up to me, or I just let it collapse. The best use of my time is to get some developers attracted to working with it again as there is still huge merit to the architecture (a testament to your work!), and nurturing a development community around ChatTheatre.com is the best way I know of how to do that.
 
-- Christopher Allen

**Comment by shentino** [comment]
Holy cow you guys did a lot while I was asleep.

I'm willing to cooperate, and I've already imported a fork of the phantasmal project into the chattheatre organization, my next planned step being to work it over and clean it up just into the website.

As for legacies I can say that dgd itself is not the only project that earned its pedigree.  SkotOS itself has been a holy grail among the mud community and I was honored to have helped it get out to the public and that was the core of my motivation, to get it open sourced and into the hands of the fans.  And I'm very glad that it's part of this chattheatre project, and the UserDB module that lets different games talk to each other through the backend is one of the cherries on top.  Perhaps other communities can use it to create their own little multi-game ecosystems.

But yeah, SkotOS kicks ass, and phantasmal and second-contract and kotaka were all directly inspired by it.

Regarding the kernel library, as long as you're familiar with the basic design principles the exact details may not be that important.  @dworkin invented the kernel library for specific purposes, and off the top of my head they include basic security, separating libraries from non libraries, and a few other things I can't remember right now.  IIRC they're documented on the DGDML, and it's called the "kernel library" IIRC precisely because it's intended to be a basic, security-enforcing wrapper around DGD's kfun api.  Personally, I think that those design principles and the motives that *DROVE* the coding in question are more important than the source code itself.

I kind of agree with dworkin's post though about not going through a bunch of red tape just to cater to legal system boondoggles.

Regarding my philosophy on copyright, I cater to and subscribe to the GPL and AGPL out of principle and I have a high amount of trust in the FSF that publishes them, and I feel a core connection to their cause in the open source/software freedom movement, and that along with Noah's blessing is why I released phantasmal under the AGPL in the first place.  I suspect that @dworkin felt the same way when he picked the AGPL himself for DGD's OSR

**Comment by shentino** [comment]
RL has been rough though and I'm kinda clumsy and disorganized in general, one of the things I was hoping to practice getting better at with managing my development of kotaka.

Give me some time to get "the paperwork" in order and get my proverbial act together.

**Comment by noahgibbs** [comment]
Cool. At this point we can get to putting the right copyright notice in Raymond's repo and cancel this PR. Sorry for the bother, Felix!

Here's the PR in Raymond's repo: https://github.com/shentino/phantasmal/pull/1

**Pull request closed without merging**
